"""Añadido device

Revision ID: 09a8492ea511
Revises: 474e66641e8d
Create Date: 2025-11-17 11:22:51.401217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a8492ea511'
down_revision = '474e66641e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amigos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device', sa.Text(length=4096), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amigos', schema=None) as batch_op:
        batch_op.drop_column('device')

    # ### end Alembic commands ###
